Repository saltstack-formulas/template-formula, pull requests merged in 2019-02, with the labels that each got.

#20 update formula with map.jinja and style guide references, improve REA…
  CHANGELOG.rst
  README.rst
  VERSION
  pillar.example
  template/config.sls
  template/defaults.yaml
  template/map.jinja
  template/osfamilymap.yaml
  template/osmap.yaml
  template/service.sls
Labels: enhancement

#23 Fix `map.jinja` and add more OSes
  CHANGELOG.rst
  VERSION
  template/map.jinja
  template/osfamilymap.yaml
  template/osmap.yaml
Labels: bump:patch

#25 map.jinja: use grains.filter_by instead of defaults.merge
  CHANGELOG.rst
  VERSION
  template/map.jinja
  template/osfingermap.yaml
Labels: bump:patch

#27 Replace obsolete `VERSION` file and replace with `FORMULA` file
  CHANGELOG.rst
  FORMULA
  VERSION
  template/osfamilymap.yaml
  template/osfingermap.yaml
  template/osmap.yaml
Labels: bump:patch

#34 Add a testing scaffold with `kitchen-ci`, `inspec` and `travis` support
  .gitignore
  .kitchen.yml
  .travis.yml
  CHANGELOG.rst
  FORMULA
  Gemfile
  pillar.example
  test/integration/default/controls/config_spec.rb
  test/integration/default/controls/packages_spec.rb
  test/integration/default/controls/services_spec.rb
  test/integration/default/inspec.yml
Labels: bump:minor, enhancement

#39 docs(contributing): add commit message formatting instructions
  CONTRIBUTING.md
  README.rst
  release-rules.js
  release.config.js
Labels: bump:patch

#26 docs(README): add authors.md
  AUTHORS.md
Labels: bump:patch

#40 refactor(kitchen): prefer `kitchen.yml` to `.kitchen.yml`
  kitchen.yml
Labels: bump:patch

#41 ci(travis): include `commitlint` stage
  .travis.yml
  CONTRIBUTING.md
  commitlint.config.js
Labels: bump:patch

#42 feat(authors): update automatically alongside `semantic-release`
  .travis.yml
  CONTRIBUTING.md
  release.config.js
Labels: bump:minor, enhancement

#38 feat(kitchen+travis): conduct tests on a wider range of platforms
  .travis.yml
  kitchen.yml
  test/integration/default/inspec.yml
Labels: bump:minor

#43 feat(toc): use `markdown-toc` directly to update inline
  .travis.yml
  CONTRIBUTING.md
  README.rst
  TOFS_pattern.md
Labels: bump:minor, enhancement

#46 refactor(tpldir): use `tpldir` or derivatives to make formula portable
  template/config.sls
  template/install.sls
  template/map.jinja
  template/service.sls
Labels: bump:patch, enhancement

#49 fix(tofs): use `tpldir` derivative `topdir` for pillar (config) paths
  template/config.sls
Labels: bug, bump:patch

#53 docs(contributing): separate `BREAKING CHANGE` under its own heading
  CONTRIBUTING.md
Labels: bump:patch
